Only track unsettled messages in ModeSecond
Azure/go-amqp pull request #36
Opened 2021-06-16 13:49 UTC by philschleier

This should fix #33 by running `addUnsettled` only in ModeSecond, same as trackCompletion:

https://github.com/Azure/go-amqp/blob/51f7e70071303e8e3e3e867fc068dedeb2f31e44/receiver.go#L53-L55

2021-06-17 05:13 UTC, serbrech requested changes

2021-06-17 05:13 UTC, serbrech commented on link.go
> +	}
let's separate the optimization from the fix.
we should still add the message to the unsettled map, but we remove the condition above.
In modeFirst, the HandleMessage func is spontaneously settling the message for you, so it removes it from the map.

we can consider an optimization in a separate PR

2021-06-17 05:16 UTC, serbrech commented on link.go
> +	}
nevermind the comment above.
didn't realize that there was also a check added in the receiver.
I think that should be good.

Would be great to implement a test to make sure we don't have regressions in the future

2021-06-17 05:19 UTC, serbrech commented
we have an integration test for this : 
https://github.com/Azure/go-amqp/blob/51f7e70071303e8e3e3e867fc068dedeb2f31e44/receiver_test.go#L42

but since we've tested against azure brokers only, it worked (no delivery tag)

2021-06-22 07:28 UTC, philschleier commented
I've removed the addUnsettled from that test.

Should we remove the entire check for unsettled messages in that test since addUnsettled is never called now?

Also, not sure you want me to do something about the fact you're only testing against azure brokers?

2021-07-08 14:59 UTC, jhendrixMSFT approved these changes
I ran the suite of SB tests with this change, looks good.

2021-07-08 14:59 UTC, merged